package database;
// Generated 13 f�vr. 2025, 17:53:57 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Classe generated by hbm2java
 */
public class Classe implements java.io.Serializable {

	private int idcours;
	private String code;
	private String nom;
	private String niveau;
	private Set courses = new HashSet(0);
	private Set etudiants = new HashSet(0);

	public Classe() {
	}

	public Classe(int idcours) {
		this.idcours = idcours;
	}

	public Classe(int idcours, String code, String nom, String niveau, Set courses, Set etudiants) {
		this.idcours = idcours;
		this.code = code;
		this.nom = nom;
		this.niveau = niveau;
		this.courses = courses;
		this.etudiants = etudiants;
	}

	public int getIdcours() {
		return this.idcours;
	}

	public void setIdcours(int idcours) {
		this.idcours = idcours;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getNiveau() {
		return this.niveau;
	}

	public void setNiveau(String niveau) {
		this.niveau = niveau;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

	public Set getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set etudiants) {
		this.etudiants = etudiants;
	}

}
