package database;
// Generated 13 f�vr. 2025, 17:53:57 by Hibernate Tools 5.4.33.Final

/**
 * EnseignantId generated by hbm2java
 */
public class EnseignantId implements java.io.Serializable {

	private String login;
	private int idens;

	public EnseignantId() {
	}

	public EnseignantId(String login, int idens) {
		this.login = login;
		this.idens = idens;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public int getIdens() {
		return this.idens;
	}

	public void setIdens(int idens) {
		this.idens = idens;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnseignantId))
			return false;
		EnseignantId castOther = (EnseignantId) other;

		return ((this.getLogin() == castOther.getLogin()) || (this.getLogin() != null && castOther.getLogin() != null
				&& this.getLogin().equals(castOther.getLogin()))) && (this.getIdens() == castOther.getIdens());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLogin() == null ? 0 : this.getLogin().hashCode());
		result = 37 * result + this.getIdens();
		return result;
	}

}
