package database;
// Generated 13 f�vr. 2025, 17:53:57 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Enseignant generated by hbm2java
 */
public class Enseignant implements java.io.Serializable {

	private EnseignantId id;
	private Personne personne;
	private String matricule;
	private Set courses = new HashSet(0);

	public Enseignant() {
	}

	public Enseignant(EnseignantId id, Personne personne) {
		this.id = id;
		this.personne = personne;
	}

	public Enseignant(EnseignantId id, Personne personne, String matricule, Set courses) {
		this.id = id;
		this.personne = personne;
		this.matricule = matricule;
		this.courses = courses;
	}

	public EnseignantId getId() {
		return this.id;
	}

	public void setId(EnseignantId id) {
		this.id = id;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
