package database;
// Generated 13 f�vr. 2025, 17:53:57 by Hibernate Tools 5.4.33.Final

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant implements java.io.Serializable {

	private EtudiantId id;
	private Classe classe;
	private Personne personne;
	private String ncarteetudiant;

	public Etudiant() {
	}

	public Etudiant(EtudiantId id, Classe classe, Personne personne) {
		this.id = id;
		this.classe = classe;
		this.personne = personne;
	}

	public Etudiant(EtudiantId id, Classe classe, Personne personne, String ncarteetudiant) {
		this.id = id;
		this.classe = classe;
		this.personne = personne;
		this.ncarteetudiant = ncarteetudiant;
	}

	public EtudiantId getId() {
		return this.id;
	}

	public void setId(EtudiantId id) {
		this.id = id;
	}

	public Classe getClasse() {
		return this.classe;
	}

	public void setClasse(Classe classe) {
		this.classe = classe;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public String getNcarteetudiant() {
		return this.ncarteetudiant;
	}

	public void setNcarteetudiant(String ncarteetudiant) {
		this.ncarteetudiant = ncarteetudiant;
	}

}
