package database;
// Generated 13 f�vr. 2025, 17:53:57 by Hibernate Tools 5.4.33.Final

/**
 * EtudiantId generated by hbm2java
 */
public class EtudiantId implements java.io.Serializable {

	private String login;
	private int idetudiant;

	public EtudiantId() {
	}

	public EtudiantId(String login, int idetudiant) {
		this.login = login;
		this.idetudiant = idetudiant;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public int getIdetudiant() {
		return this.idetudiant;
	}

	public void setIdetudiant(int idetudiant) {
		this.idetudiant = idetudiant;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EtudiantId))
			return false;
		EtudiantId castOther = (EtudiantId) other;

		return ((this.getLogin() == castOther.getLogin()) || (this.getLogin() != null && castOther.getLogin() != null
				&& this.getLogin().equals(castOther.getLogin())))
				&& (this.getIdetudiant() == castOther.getIdetudiant());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLogin() == null ? 0 : this.getLogin().hashCode());
		result = 37 * result + this.getIdetudiant();
		return result;
	}

}
